pipeline:
  name: feb13 pipe1
  identifier: feb13_pipe1
  projectIdentifier: AmitTest
  orgIdentifier: GitXOrg
  tags: {}
  stages:
    - stage:
        name: a1
        identifier: a1
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Shell Script_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo 'hi'
                          exit 1
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
