pipeline:
  name: issueCheck12Dec
  identifier: issueCheck12Dec
  projectIdentifier: AmitTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: A1
        identifier: A1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: fr
                  identifier: fr
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
    - stage:
        name: A34
        identifier: A34
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: Asd45
                  identifier: Asd45
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups: <+input>
                    approverInputs: []
        tags: {}
    - stage:
        name: yt
        identifier: yt
        template:
          templateRef: DeployTypeT1
          versionLabel: "1"
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: sde
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
