pipeline:
  name: parentPipeline
  identifier: parentPipeline
  projectIdentifier: AmitTest
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: s23
        identifier: s23
        description: ""
        type: Pipeline
        spec:
          org: Pipelines_NonK8s_Org_NG
          pipeline: ChildRemoteNonDefault
          project: AmitTest
          inputSetReferences:
            - inputSetp19
    - stage:
        name: s44
        identifier: s44
        description: ""
        type: Pipeline
        spec:
          org: Pipelines_NonK8s_Org_NG
          pipeline: ChildNonDefaultBranchPipe19Sept
          project: AmitTest
          inputSetReferences:
            - inputSetSpet19Set1
