pipeline:
  name: Per456
  identifier: Per456
  projectIdentifier: ProdMigration
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: As34
        identifier: As34
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: df45
                  identifier: df45
                  template:
                    templateRef: Step_in_nonDefault_branch
                    versionLabel: v1
        tags: {}
