pipeline:
  name: pipelineBNov24
  identifier: pipelineBNov24
  projectIdentifier: TractableTest
  orgIdentifier: default
  tags: {}
  stages:
    - parallel:
        - stage:
            name: A
            identifier: A
            template:
              templateRef: account.Deploy_ConfigMap
              versionLabel: v1.0
              templateInputs:
                type: Deployment
                spec:
                  serviceConfig:
                    serviceRef: <+input>
                    serviceDefinition:
                      type: Kubernetes
                      spec:
                        manifests:
                          - manifest:
                              identifier: abc
                              type: HelmChart
                              spec:
                                store:
                                  type: Http
                                  spec:
                                    connectorRef: <+input>
                                chartName: <+input>
                                chartVersion: <+input>
                  infrastructure:
                    environmentRef: <+input>
                    infrastructureDefinition:
                      type: KubernetesDirect
                      spec:
                        connectorRef: <+input>
                        namespace: <+input>
        - stage:
            name: B
            identifier: B
            template:
              templateRef: account.InlineStage
              versionLabel: v1
              templateInputs:
                type: Approval
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: A2
                          type: HarnessApproval
                          spec:
                            approvers:
                              userGroups: <+input>
    - parallel:
        - stage:
            name: C
            identifier: C
            template:
              templateRef: Delete_and_Apply
              versionLabel: "1.0"
              templateInputs:
                type: Deployment
                spec:
                  serviceConfig:
                    serviceRef: <+input>
                    serviceDefinition:
                      type: Kubernetes
                      spec:
                        artifacts:
                          primary:
                            type: DockerRegistry
                            spec:
                              imagePath: <+input>
                              tag: <+input>
                  infrastructure:
                    environmentRef: <+input>
                    infrastructureDefinition:
                      type: KubernetesDirect
                      spec:
                        connectorRef: <+input>
                variables:
                  - name: BRANCH
                    type: String
                    value: <+input>
                  - name: MANIFEST
                    type: String
                    value: <+input>
                when:
                  condition: <+input>
        - stage:
            name: D
            identifier: D
            template:
              templateRef: Build
              versionLabel: "1.0"
              templateInputs:
                type: CI
                spec:
                  infrastructure:
                    type: KubernetesDirect
                    spec:
                      connectorRef: <+input>
                  execution:
                    steps:
                      - parallel:
                          - step:
                              identifier: Restore_Cache
                              type: RestoreCacheS3
                              spec:
                                connectorRef: <+input>
                      - step:
                          identifier: Yarn_Build
                          type: Run
                          spec:
                            image: <+input>
                      - parallel:
                          - step:
                              identifier: Update_Cache
                              template:
                                templateInputs:
                                  type: SaveCacheS3
                                  spec:
                                    key: <+input>
                                    override: <+input>
                variables:
                  - name: CLUSTER_ENV
                    type: String
                    value: <+input>.allowedValues(dev,infra-eu)
                when:
                  condition: <+input>
    - stage:
        name: A34
        identifier: A34
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  name: gghh
                  identifier: gghh
                  template:
                    templateRef: account.inlineStep45
                    versionLabel: v2
                    templateInputs:
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
        tags: {}
  properties:
    ci:
      codebase:
        connectorRef: <+input>
        repoName: <+input>
        build: <+input>
