pipeline:
  name: pipeA24Nov
  identifier: pipeA24Nov
  projectIdentifier: TractableTest
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Ac
        identifier: Ac
        template:
          templateRef: Delete_and_Apply
          versionLabel: "1.0"
          templateInputs:
            type: Deployment
            spec:
              serviceConfig:
                serviceRef: <+input>
                serviceDefinition:
                  type: Kubernetes
                  spec:
                    artifacts:
                      primary:
                        type: DockerRegistry
                        spec:
                          imagePath: <+input>
                          tag: <+input>
              infrastructure:
                environmentRef: <+input>
                infrastructureDefinition:
                  type: KubernetesDirect
                  spec:
                    connectorRef: <+input>
            variables:
              - name: BRANCH
                type: String
                value: <+input>
              - name: MANIFEST
                type: String
                value: <+input>
            when:
              condition: <+input>
    - stage:
        name: fgr
        identifier: fgr
        template:
          templateRef: account.Deploy_SecretStore
          versionLabel: v1.0
          templateInputs:
            type: Deployment
            spec:
              serviceConfig:
                serviceRef: <+input>
                serviceDefinition:
                  type: Kubernetes
                  spec:
                    manifests:
                      - manifest:
                          identifier: acc1
                          type: HelmChart
                          spec:
                            store:
                              type: Http
                              spec:
                                connectorRef: <+input>
                            chartName: <+input>
                            chartVersion: <+input>
              infrastructure:
                environmentRef: <+input>
                infrastructureDefinition:
                  type: KubernetesDirect
                  spec:
                    connectorRef: <+input>
                    namespace: <+input>
