pipeline:
  name: pipe23Nov1
  identifier: pipe23Nov1
  projectIdentifier: Amit23Nov
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: A345
        identifier: A345
        description: abc
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: A3
                  identifier: A3
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
