template:
  name: prod123
  identifier: prod123
  versionLabel: v1
  type: Step
  tags: {}
  spec:
    type: HarnessApproval
    timeout: 1d
    spec:
      approvalMessage: Please review the following information and approve the pipeline progression update
      includePipelineExecutionHistory: true
      approvers:
        userGroups: <+input>
        minimumCount: 1
        disallowPipelineExecutor: false
      approverInputs: []
