pipeline:
  name: pipe23nov
  identifier: pipe23nov
  projectIdentifier: check23
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Q1
        identifier: Q1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  name: W22
                  identifier: W22
                  type: HarnessApproval
                  timeout: 1d
                  spec:
                    approvalMessage: |-
                      Please review the following information
                      and approve the pipeline progression
                    includePipelineExecutionHistory: true
                    approvers:
                      minimumCount: 1
                      disallowPipelineExecutor: false
                      userGroups:
                        - account._account_all_users
                    approverInputs: []
        tags: {}
