pipeline:
  name: Before git sync enable
  identifier: Before_git_sync_enable
  projectIdentifier: ProdMigration
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: A1
        identifier: A1
        template:
          templateRef: Stage_before_gitsync
          versionLabel: v1
          templateInputs:
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: A2
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
