pipeline:
  name: before git sync
  identifier: before_git_sync
  projectIdentifier: TestGitSyncMigration
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: A1
        identifier: A1
        description: ""
        type: Approval
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: script1
                  identifier: script1
                  spec:
                    shell: Bash
                    onDelegate: true
                    source:
                      type: Inline
                      spec:
                        script: echo 'amit'
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
    - stage:
        name: B1
        identifier: B1
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: account.K8sManualDevXQCAQO0QWAZ
              namespace: abc
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  name: hgt
                  identifier: hgt
                  template:
                    templateRef: RunStep123
                    versionLabel: v1
  properties:
    ci:
      codebase:
        connectorRef: account.github_Account_level_connector
        repoName: Testbug
        build: <+input>
